language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install numpy scipy
  - pip install --upgrade numpy scipy
  - pip install -e .
script: check/run_test
